In [1]:
import numpy as np

In [2]:
# Task 1
arr = np.arange(10)
print("Array")
print(arr)

arr[0],arr[9] = arr[9],arr[0]
print("After swapping")
print(arr)

Array
[0 1 2 3 4 5 6 7 8 9]
After swapping
[9 1 2 3 4 5 6 7 8 0]


In [3]:
#Task 2
arr = np.empty(10, dtype = int)
for i in range(10):
    n = int(input("Enter value : "))
    arr[i] = n
new = np.array_split(arr,2)
print(" Array filled by taking user's input")    
print(arr)

print("Splitted arrays")
print(new)


    
    

Enter value : 1
Enter value : 2
Enter value : 3
Enter value : 4
Enter value : 5
Enter value : 6
Enter value : 7
Enter value : 8
Enter value : 9
Enter value : 10
 Array filled by taking user's input
[ 1  2  3  4  5  6  7  8  9 10]
Splitted arrays
[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [4]:
# Task 3
odd = 0
even = 0
pos = 0
neg = 0
zeros = 0
prime = 0
com = 0

for i in range(10):
    n = int(input("Enter number"))
    if n%2 == 0:
        even = even + 1
    if n%2 == 1:
        odd = odd + 1
    if n > 0:
        pos = pos + 1
    if n < 0:
        neg = neg + 1
    if n == 0:
        zeros = zeros + 1
    if n > 1:
        for i in range(2,n):
            if n%i == 0:
                com = com + 1
                break
        else:
            prime = prime + 1
    else:
        print(" ")
        
print("Number of Even Numbers : ",even)
print("Number of Odd Numbers : ",odd)
print("Number of Positive Numbers : ",pos)
print("Number of Negative Numbers : ",neg)
print("Number of Zero Numbers : ",zeros)
print("Number of prime Numbers : ",prime)
print("Number of composite Numbers : ",com)

Enter number0
 
Enter number0
 
Enter number-5
 
Enter number2
Enter number5
Enter number7
Enter number6
Enter number4
Enter number3
Enter number10
Number of Even Numbers :  6
Number of Odd Numbers :  4
Number of Positive Numbers :  7
Number of Negative Numbers :  1
Number of Zero Numbers :  2
Number of prime Numbers :  4
Number of composite Numbers :  3


In [5]:
# Task 4

arr = np.array([0,3,6,7,9])     #1=dimensional array
print(arr)

[0 3 6 7 9]


In [6]:
arr = np.array([[9,8,7,6],[3,2,1,0]])    #2-dimensional array
print(arr)
arr.shape

[[9 8 7 6]
 [3 2 1 0]]


(2, 4)

In [7]:
arr = np.arange(0,20,2)
print(arr)
arr.shape             # shape incorrect

[ 0  2  4  6  8 10 12 14 16 18]


(10,)

In [8]:
# Reshaping
arr = arr.reshape(arr.shape[0],1)   
arr.shape

(10, 1)

In [9]:
arr = np.linspace(0,3,12)    #Add evenly spaced values to the array
print(arr)
arr.shape

[0.         0.27272727 0.54545455 0.81818182 1.09090909 1.36363636
 1.63636364 1.90909091 2.18181818 2.45454545 2.72727273 3.        ]


(12,)

In [10]:
arr = np.linspace(0,3,12).reshape(12,1)    #reshaping
arr.shape

(12, 1)

In [11]:
arr = np.zeros((3,4))  # array of zeros  
print(arr)
arr.shape

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


(3, 4)

In [12]:
arr = np.zeros((3,4), dtype = int)    # int type array of zeros
print(arr)
arr.shape

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


(3, 4)

In [13]:
 
arr = np.random.random((3,3)) # array of random values
print(arr)
arr.shape


[[0.99943098 0.50156082 0.99121261]
 [0.21007027 0.84218474 0.37574587]
 [0.05937319 0.17084461 0.80823988]]


(3, 3)

In [14]:

arr = np.empty((3,2), dtype = int) # Empty array creation
print(arr)
arr.shape

[[ 0  0]
 [ 5  0]
 [10  0]]


(3, 2)

In [15]:

arr = np.array([9,3,6,5,8]) # to get the lenth of an array
len(arr)

5

In [16]:
arr = np.array([[2,3,6,5]]) # here it len() returns the number of rows of 2d array 
len(arr)

1

In [17]:
arr = np.zeros((2,4)) # array of zeros with float type 
print(arr)
arr = arr.astype(int)    # conversion to int
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]]


In [18]:

arr = np.array([[0,2,3,6],[4,5,6,7]])
arr_2 = np.copy(arr)                    # it creates copy of array
print(arr_2)

[[0 2 3 6]
 [4 5 6 7]]


In [19]:
arr = np.array([1,2,3,4])
arr_2 = np.array([[5,6],[7,8]])
arr = np.append(arr,arr_2)            # appending arrays
print(arr)
arr.shape

[1 2 3 4 5 6 7 8]


(8,)

In [20]:
arr_2 = arr.reshape(1,arr.shape[0])    
print(arr_2)                         # reshaping
arr_2.shape

[[1 2 3 4 5 6 7 8]]


(1, 8)

In [21]:
print(arr_2)
arr_2 = np.delete(arr_2,4,axis=1)   # it deletes 4th index or 5th value
print(arr_2)

[[1 2 3 4 5 6 7 8]]
[[1 2 3 4 6 7 8]]


In [22]:
# combining arrays
arr = np.array([[4,5,6]])
arr_2 = np.array([[1,2,3],[7,8,6]])
print(arr)
print(" ")
print(arr_2)
print(" ")
vec = np.concatenate((arr,arr_2),axis=0)
print(vec)

[[4 5 6]]
 
[[1 2 3]
 [7 8 6]]
 
[[4 5 6]
 [1 2 3]
 [7 8 6]]


In [23]:
# combining arrays vertically
vec = np.array([[1,2,3,6]])
vec2 = np.array([[2,8,4,5],[1,4,8,4]])
print(vec)
print(" ")
print(vec2)
print(" ")
vec3 = np.vstack((vec,vec2))
print(vec3)

[[1 2 3 6]]
 
[[2 8 4 5]
 [1 4 8 4]]
 
[[1 2 3 6]
 [2 8 4 5]
 [1 4 8 4]]


In [24]:
# combining arrays horizontally
vect = np.array([[4,1,4,3],[4,7,0,6]])
vect2 = np.array([[6,9,5,1],[8,7,3,1]])
print(vect)
print(" ")
print(vect2)
print(" ")
vect3 = np.hstack((vect,vect2))
print(vect3)

[[4 1 4 3]
 [4 7 0 6]]
 
[[6 9 5 1]
 [8 7 3 1]]
 
[[4 1 4 3 6 9 5 1]
 [4 7 0 6 8 7 3 1]]


In [25]:
# Flattens a 2d array to 1d

A = np.array([[7,5,3,8],[1,4,6,2]])
B = A.flatten()
print(B)

[7 5 3 8 1 4 6 2]


In [26]:
# transpose of matrix

vect = np.array([[1,5,8,3],[4,6,7,1]])
print(vect.shape)
print("")
vect = vect.T
print(vect.shape)

(2, 4)

(4, 2)


In [27]:
# inverse of matrix
A = np.array([[4,5,6],[7,8,9],[1,2,3]])
B = np.linalg.inv(A)
print(B)

[[ 9.00719925e+15 -4.50359963e+15 -4.50359963e+15]
 [-1.80143985e+16  9.00719925e+15  9.00719925e+15]
 [ 9.00719925e+15 -4.50359963e+15 -4.50359963e+15]]
